development:
  adapter: postgresql
  encoding: unicode
  database: comments
  pool: 5
  username: momwebsite
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: comments
  pool: 5
  username: momwebsite
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: comments
  pool: 5
  username: momwebsite
  password: 