# development:
#   adapter: postgresql
#   encoding: unicode
#   database: guestbook
#   pool: 5
#   username: momwebsite
#   password: 

test:
  adapter: postgresql
  encoding: unicode
  database: guestbook
  pool: 5
  username: momwebsite
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: guestbook
  pool: 5
  username: momwebsite
  password: 

 
development:
 adapter: sqlite3
 database: db/development.sqlite3
 pool: 5
 timeout: 5000