development:
  adapter: postgresql
  encoding: unicode
  database: microposts
  pool: 5
  username: will
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: microposts
  pool: 5
  username: will
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: microposts
  pool: 5
  username: will
  password: